debug: false
cdn_system:
  priority: [custom, local, npm, static, cdnjs]
  system_config:
    custom:
      busuanzi: https://jsd.onmicrosoft.cn/npm/penndu@17.0.0/bsz.js
      fontawesome: https://font.onmicrosoft.cn/font6pro@6.7.1/css/all.min.css
csp:
  enable: false
replace:
dns_prefetch:
  - https://unpkg.onmicrosoft.cn
  - https://unpkg.com
navbar:
  visiable: always
  logo:
    img: /favicon.ico
  menu:
    - name: 科 A 作品
      icon: fa-solid fa-head-side-brain
      rows:
        - name: 混沌之脑
          icon: fa-solid fa-mind-share
          url: /categories/混沌之脑/
        - name: 命运石之门
          icon: fa-solid fa-cog
          url: /categories/命运石之门/
        - name: 机器人笔记
          icon: fa-solid fa-robot
          url: /categories/机器人笔记/
        - name: 混沌之子
          icon: fa-solid fa-eye
          url: /categories/混沌之子/
        - name: 超自然 9 人组
          icon: fa-solid fa-star-of-david
          url: /categories/超自然9人组/
    - name: 关于本站
      icon: fa-solid fa-info
      url: /about/
    - name: 科 A 资源站
      icon: fa-solid fa-server fa-bounce
      url: https://drive.sci-adv.cc/
      target: _blank
    - name: 开往
      icon: fa-solid fa-subway
      url: https://www.travellings.cn/go.html
      target: _blank
    - name: 更多
      icon: fa-solid fa-ellipsis-v
      rows:
        - name: 夜间模式
          icon: fa-solid fa-moon
          toggle: darkmode
          target: _blank
        - name: 本站源代码
          icon: fa-solid fa-code
          url: https://github.com/MCSeekeri/sciadv
          target: _blank
        - name: hr
        - name: 科学 ADV 中文 Wiki
          icon: fa-solid fa-book
          url: https://sci-adv.cc/wiki/%E9%A6%96%E9%A1%B5
          target: _blank
        - name: devil 的 CD 整理 (谷歌文档)
          icon: fa-solid fa-compact-disc
          url: https://docs.google.com/document/d/1iy8uuAqUtINnfYP_DYmCStDTz_CA6O9W/
          target: _blank
        - name: 未来同人研究所
          icon: fa-solid fa-user-edit
          url: https://space.bilibili.com/7348022/
          target: _blank
cover:
  height_scheme: half
  display:
    others: true
  background: https://unpkg.com/mcseekeri@1.2.6/img/cover/cover6.webp
  logo:
  title: ""
  subtitle: ""
  search: ""
  features:
    - name: 归档
      icon: fa-solid fa-archive
      url: /archives/
    - name: 小说
      icon: fa-solid fa-file-alt
      url: /tags/小说/
    - name: 同人
      icon: fa-solid fa-user-edit
      url: /tags/同人/
    - name: 石学
      icon: fa-solid fa-books
      url: /tags/讨论探究/
    - name: 关于
      icon: fa-solid fa-user-circle
      url: /about/
article:
  preview:
    pin_icon: https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f4cc.svg
    line_style: dashed
    author: true
  body:
    top_meta: [author, tags, date, wordcount, walinecount]
    footer_widget:
      recommended_article:
        layout: post
        placeholder_img: https://lib.sci-adv.cc/favicon.ico
      related_posts:
        placeholder_img: /favicon.ico
      copyright:
        enable: true
        permalink: "本文永久链接是："
        content:
          - "本文遵循 署名-非商业性使用-相同方式共享 4.0 国际 (CC BY-NC-SA 4.0) 协议"
          - permalink
        custom: true
        customData:
          default: type4
    meta_library:
      author:
        avatar: https://unpkg.com/mcseekeri@1.2.6/avatar/mp.webp
        name: Anonymous
        url: /
      share:
        - id: qq
          img: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/logo/128/qq.png
        - id: qzone
          img: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/logo/128/qzone.png
        - id: weibo
          img: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/logo/128/weibo.png
        - id: telegram
          img: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/logo/128/telegram.png

comments:
  service: waline
  waline:
    placeholder: 欢迎在此发表您对本文的看法，本站评论只需填写昵称和接受回复用的邮箱
    requiredFields: [nick, mail]
    dark: "auto"
    serverURL: https://comments.sci-adv.cc
    recaptchaV3Key: 6Lf9KTAbAAAAALfqwFyJmbRTABDc3MwyCKo696gp
    emoji:
      - https://cdn.jsdelivr.net/gh/GamerNoTitle/ValineCDN@master/QQ
      - https://cdn.jsdelivr.net/gh/GamerNoTitle/ValineCDN@master/Tieba
      - https://cdn.jsdelivr.net/gh/GamerNoTitle/ValineCDN@master/Tieba-New
      - https://cdn.jsdelivr.net/gh/GamerNoTitle/ValineCDN@master/weibo
      - https://cdn.jsdelivr.net/gh/GamerNoTitle/ValineCDN@master/Coolapk
      - https://cdn.jsdelivr.net/gh/GamerNoTitle/ValineCDN@master/Heybox
      - https://cdn.jsdelivr.net/gh/GamerNoTitle/ValineCDN@master/bilibili2233/
      - https://cdn.jsdelivr.net/gh/GamerNoTitle/ValineCDN@master/Menhera-chan
    reaction:
      - https://unpkg.com/@waline/emojis@1.3.0/tieba/tieba_agree.png
      - https://unpkg.com/@waline/emojis@1.3.0/tieba/tieba_doubt.png
      - https://unpkg.com/@waline/emojis@1.3.0/tieba/tieba_heart.png
      - https://unpkg.com/@waline/emojis@1.3.0/tieba/tieba_lovely.png
      - https://unpkg.com/@waline/emojis@1.3.0/tieba/tieba_rage.png
      - https://unpkg.com/@waline/emojis@1.3.0/tieba/tieba_cry.png
      - https://unpkg.com/@waline/emojis@1.3.0/tieba/tieba_awkward.png
      - https://unpkg.com/@waline/emojis@1.3.0/tieba/tieba_vomit.png
sidebar:
  for_page: [lastupdate, notice, tagcloud, webinfo]
  widget_library:
    blogger:
      avatar: https://unpkg.com/mcseekeri@1.2.6/avatar/amadeus.webp
      title: 科学 ADV 图书馆
      subtitle: 致力于科 A 相关内容的搜集与整理
      jinrishici: false
      social:
        - icon: fa-solid fa-envelope
          url: mailto:hiyajo.maho@outlook.jp
        - icon: fab fa-github
          url: https://github.com/mcseekeri/sciadv
    category:
      display: [desktop, mobile]
      header:
        url: /categories/
    tagcloud:
      header:
        url: /tags/
      min_font: 18
      max_font: 26

    qrcode:
      images:
        - https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/qrcode/github@volantis.png
        - https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/qrcode/github@volantis.png
    webinfo:
      display: [desktop, mobile]
      type:
        runtime:
          enable: true
          data: "2021/01/09"
        wordcount:
          enable: true
    notice:
      class: text
      display: [desktop, mobile]
      header:
        icon: fad fa-siren-on
        title: 站点公告
      content:
        - 「然后呢,我,把这个混帐的站点,发布了。」
        - 欢迎来到科学ADV图书馆，本站致力于收集科学ADV系列所有衍生小说。
        - 站点支持离线访问及作为程序安装到设备上，方便用户查询内容。
        - 如果您访问本站遇到了一些问题，请尝试清除浏览器数据之后访问。
        - 预祝看的愉快,有问题欢迎前往[关于页面](/about/)进行留言
tag_plugins:
  note:
    icon: '\f054'
    color: ""
    iconfont: "Font Awesome 6 Pro"
  link:
    placeholder: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/logo/256/safari.png

site_footer:
  layout: [aplayer, badge, br, analytics, copyright]
  source: https://github.com/mcseekeri/sciadv

  copyright: "本站内容来源自网络 所有权归作者所有"
  badge: "[![commit](https://img.shields.io/github/last-commit/MCSeekeri/sciadv?style=for-the-badge)](https://github.com/MCSeekeri/sciadv) [![star](https://img.shields.io/github/stars/MCSeekeri/sciadv?style=for-the-badge)](https://github.com/MCSeekeri/sciadv) [![size](https://img.shields.io/github/repo-size/MCSeekeri/sciadv?style=for-the-badge)](https://github.com/MCSeekeri/sciadv) [![code size](https://img.shields.io/github/languages/code-size/MCSeekeri/sciadv?logo=code%20size&style=for-the-badge)](https://github.com/MCSeekeri/sciadv) [![status](https://img.shields.io/uptimerobot/ratio/m785802121-f726e102d93b206615b80ae4?style=for-the-badge)](https://status.mcseekeri.com/)"

plugins:
  sitesjs:
    enable: false
  friendsjs:
    enable: false
  contributorsjs:
    enable: false

  lazyload:
    onlypost: true

  prismjs:
    copy_code: false
    js:
      - https://unpkg.com/prismjs/components/prism-core.min.js
      - https://unpkg.com/prismjs/plugins/autoloader/prism-autoloader.min.js
      - https://unpkg.com/prismjs/plugins/line-numbers/prism-line-numbers.min.js
    css:
      - https://unpkg.com/prismjs/themes/prism-dark.css
      - https://unpkg.com/prismjs/plugins/line-numbers/prism-line-numbers.css

  scrollreveal:
    enable: true
    distance: 32px
    duration: 500
  wordcount:
    enable: true
  busuanzi:
    enable: true

  nodewaves:
    enable: true

  parallax:
    images:
      - https://unpkg.com/mcseekeri@1.2.6/img/cover/cover1.webp
      - https://unpkg.com/mcseekeri@1.2.6/img/cover/cover2.webp
      - https://unpkg.com/mcseekeri@1.2.6/img/cover/cover3.webp
      - https://unpkg.com/mcseekeri@1.2.6/img/cover/cover4.webp
      - https://unpkg.com/mcseekeri@1.2.6/img/cover/cover5.webp
      - https://unpkg.com/mcseekeri@1.2.6/img/cover/cover6.webp
      - https://unpkg.com/mcseekeri@1.2.6/img/cover/cover7.webp
      - https://unpkg.com/mcseekeri@1.2.6/img/cover/cover8.webp
      - https://unpkg.com/mcseekeri@1.2.6/img/cover/cover9.webp
      - https://unpkg.com/mcseekeri@1.2.6/img/cover/cover10.webp
      - https://unpkg.com/mcseekeri@1.2.6/img/cover/cover11.webp
      - https://unpkg.com/mcseekeri@1.2.6/img/cover/cover12.webp
      - https://unpkg.com/mcseekeri@1.2.6/img/cover/cover13.webp
      - https://unpkg.com/mcseekeri@1.2.6/img/cover/cover14.webp
      - https://unpkg.com/mcseekeri@1.2.6/img/cover/cover15.webp
      - https://unpkg.com/mcseekeri@1.2.6/img/cover/cover16.webp
  aplayer:
    enable: true
    id: 6608242431
    fixed: true
    autoHide: false

  darkmode:
    enable: true

  killNoScript:
    enable: false
  message:
    enable: true
  tidio:
    id: cfeex4okbrrdpt6edk1w3hfsbymjft8x
  menus:
    link:
      - {
          id: "source_docs",
          name: "本站源码",
          icon: "fa-solid fa-code-branch",
          link: "https://github.com/mcseekeri/sciadv",
          group: "link",
        }
custom_css:
  scrollbar:
    size: 12px
    border: 3px
  body:
    effect: [shadow]
  fontfamily:
    logofont:
      fontfamily: '"Roboto", "Noto Serif SC", "PingFang SC", "Microsoft Yahei UI", "Microsoft Yahei", sans-serif'
    bodyfont:
      fontfamily: '"Roboto", "Noto Serif SC", "PingFang SC", "Microsoft Yahei UI", "Microsoft Yahei", sans-serif'
    codefont:
      fontfamily: '"Roboto", "Noto Serif SC", "PingFang SC", "Microsoft Yahei UI", "Microsoft Yahei", sans-serif'
seo:
  robots:
    home_other_pages: index,follow
    archive: index,follow
    category: index,follow
    tag: index,follow

open_graph:
  image: /favicon.ico
structured_data:
  enable: false
  data:
    person:
      sns:
        - https://github.com/MCSeekeri
    logo:
      path: /favicon.ico
