# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 科学ADV图书馆
subtitle: ''
description: 本站致力于科学ADV作品(如命运石之门)小说及同人内容收集
keywords: 小说,命运石之门,科学ADV,混沌之子,混沌之脑,
author: MCSeekeri
language: zh-CN
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://example.com/child' and root as '/child/'
url: https://sciadv.top
root: /
permalink: archives/:abbrlink/
permalink_defaults:
pretty_urls:
  trailing_index: false # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: false # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: 

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace: ''
  wrap: true
  hljs: true
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 20
  order_by: -date
  pagination_dir: page

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 20
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
plugins:
  - hexo-reference

theme: volantis

hexo_submit_urls_to_search_engine:
  submit_condition: count #链接被提交的条件，可选值：count | period 现仅支持count
  count: 50 # 提交最新的10个链接
  period: 1600 # 提交修改时间在 1600 秒内的链接
  google: 1 # 是否向Google提交，可选值：1 | 0（0：否；1：是）
  bing: 1 # 是否向bing提交，可选值：1 | 0（0：否；1：是）
  baidu: 1 # 是否向baidu提交，可选值：1 | 0（0：否；1：是）
  txt_path: submit_urls.txt ## 文本文档名， 需要推送的链接会保存在此文本文档里
  baidu_host: https://sciadv.top 
  baidu_token: 0
  bing_host: https://sciadv.top 
  bing_token: 0
  google_host: https://sciadv.top 
  google_key_file: push.json
  google_proxy: 0 # 向谷歌提交网址所使用的系统 http 代理，填 0 不使用
  replace: 1  # 是否替换链接中的部分字符串，可选值：1 | 0（0：否；1：是）
  find_what: sciadv.mcseekeri.top
  replace_with: sciadv.top

import:
    link:
      - <link rel="preconnect" href="https://ha3d7xjx.api.lncldglobal.com">
      - <link rel="preconnect" href="https://fonts.googleapis.com">
      - <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      - <link href="https://fonts.googleapis.com/css2?family=Noto+Serif+SC:wght@400;900&family=Roboto:wght@300;900&display=swap" rel="stylesheet" media="print" onload="this.media='all'">

nofollow:
  enable: true
  field: site
  exclude:
    - 'sciadv.top'
    - 'mcseekeri.top'
  
abbrlink:
  alg: crc32      #support crc16(default) and crc32
  rep: hex        #support dec(default) and hex
  drafts: false   #(true)Process draft,(false)Do not process draft. false(default) 
  # Generate categories from directory-tree
  # depth: the max_depth of directory-tree you want to generate, should > 0
  auto_category:
     enable: true  #true(default)
     depth:        #3(default)
     over_write: false 
  auto_title: false #enable auto title, it can auto fill the title by path
  auto_date: false #enable auto date, it can auto fill the date by time today
  force: false #enable force mode,in this mode, the plugin will ignore the cache, and calc the abbrlink for every post even it already had abbrlink.

baidu_analytics_key: 633c3b07ea8711cceacf3394bcae9687
google_analytics_key: G-SSK4MM0RCG

algolia:
  applicationID: NZUPA1KZ8D
  apiKey: 88c852dba6c38d051f025b32915f797a
  indexName: Sciadv
  chunkSize: 5000

sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  - type: git
    repository: 
      github: git@github.com:MCSeekeri/sciadv-site
      coding: git@e.coding.net:mcseekeri/sciadv/sciadv-site
      gitee: git@gitee.com:mcseekeri/sciadv-site
    branch: master
  - type: cjh_bing_url_submitter
  - type: cjh_baidu_url_submitter
  - type: cjh_google_url_submitter
