debug: false
cdn_system:
  priority: [custom, local, npm, static, cdnjs]
  system_config:
    custom:
      busuanzi: https://jsd.onmicrosoft.cn/npm/penndu@17.0.0/bsz.js
      fontawesome: https://font.onmicrosoft.cn/font6pro@6.7.1/css/all.min.css
csp:
  enable: false
replace:
dns_prefetch:
  - https://unpkg.onmicrosoft.cn
  - https://unpkg.com
navbar:
  visiable: always
  logo:
    img: /favicon.ico
  menu:
    - name: 科 A 作品
      icon: fa-solid fa-head-side-brain
      rows:
        - name: 混沌之脑
          icon: fa-solid fa-mind-share
          url: /categories/混沌之脑/
        - name: 命运石之门
          icon: fa-solid fa-cog
          url: /categories/命运石之门/
        - name: 机器人笔记
          icon: fa-solid fa-robot
          url: /categories/机器人笔记/
        - name: 混沌之子
          icon: fa-solid fa-eye
          url: /categories/混沌之子/
        - name: 超自然 9 人组
          icon: fa-solid fa-star-of-david
          url: /categories/超自然9人组/
    - name: 关于本站
      icon: fa-solid fa-info
      url: /about/
    - name: 科 A 资源站
      icon: fa-solid fa-server fa-bounce
      url: https://drive.sci-adv.cc/
      target: _blank
    - name: 开往
      icon: fa-solid fa-subway
      url: https://www.travellings.cn/go.html
      target: _blank
    - name: 更多
      icon: fa-solid fa-ellipsis-v
      rows:
        - name: 夜间模式
          icon: fa-solid fa-moon
          toggle: darkmode
          target: _blank
        - name: 本站源代码
          icon: fa-solid fa-code
          url: https://github.com/MCSeekeri/sciadv
          target: _blank
        - name: hr
        - name: 科学 ADV 中文 Wiki
          icon: fa-solid fa-book
          url: https://sci-adv.cc/wiki/%E9%A6%96%E9%A1%B5
          target: _blank
        - name: devil 的 CD 整理 (谷歌文档)
          icon: fa-solid fa-compact-disc
          url: https://docs.google.com/document/d/1iy8uuAqUtINnfYP_DYmCStDTz_CA6O9W/
          target: _blank
        - name: 未来同人研究所
          icon: fa-solid fa-user-edit
          url: https://space.bilibili.com/7348022/
          target: _blank
cover:
  height_scheme: half
  display:
    others: true
  background: https://unpkg.com/mcseekeri@1.2.6/img/cover/cover6.webp
  logo:
  title: ""
  subtitle: ""
  search: ""
  features:
    - name: 归档
      icon: fa-solid fa-archive
      url: /archives/
    - name: 小说
      icon: fa-solid fa-file-alt
      url: /tags/小说/
    - name: 同人
      icon: fa-solid fa-user-edit
      url: /tags/同人/
    - name: 石学
      icon: fa-solid fa-books
      url: /tags/讨论探究/
    - name: 关于
      icon: fa-solid fa-user-circle
      url: /about/
article:
  preview:
    pin_icon: https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f4cc.svg
    line_style: dashed
    author: true
  body:
    top_meta: [author, tags, date, wordcount, walinecount]
    footer_widget:
      recommended_article:
        layout: post
        placeholder_img: https://lib.sci-adv.cc/favicon.ico
      related_posts:
        placeholder_img: /favicon.ico
      copyright:
        enable: true
        permalink: "本文永久链接是："
        content:
          - "本文遵循 署名-非商业性使用-相同方式共享 4.0 国际 (CC BY-NC-SA 4.0) 协议"
          - permalink
        custom: true
        customData:
          default: type4
    meta_library:
      author:
        avatar: https://unpkg.com/mcseekeri@1.2.6/avatar/mp.webp
        name: Anonymous
        url: /
      share:
        - id: qq
          img: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/logo/128/qq.png
        - id: qzone
          img: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/logo/128/qzone.png
        - id: weibo
          img: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/logo/128/weibo.png
        - id: telegram
          img: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/logo/128/telegram.png

comments:
  service: waline
  waline:
    placeholder: 欢迎在此发表您对本文的看法，本站评论只需填写昵称和接受回复用的邮箱
    requiredFields: [nick, mail]
    serverURL: https://comments.sci-adv.cc
    recaptchaV3Key: 6Lf9KTAbAAAAALfqwFyJmbRTABDc3MwyCKo696gp
    emoji:
      - https://cdn.jsdelivr.net/gh/GamerNoTitle/ValineCDN@master/QQ
      - https://cdn.jsdelivr.net/gh/GamerNoTitle/ValineCDN@master/Tieba
      - https://cdn.jsdelivr.net/gh/GamerNoTitle/ValineCDN@master/Tieba-New
      - https://cdn.jsdelivr.net/gh/GamerNoTitle/ValineCDN@master/weibo
      - https://cdn.jsdelivr.net/gh/GamerNoTitle/ValineCDN@master/Coolapk
      - https://cdn.jsdelivr.net/gh/GamerNoTitle/ValineCDN@master/Heybox
      - https://cdn.jsdelivr.net/gh/GamerNoTitle/ValineCDN@master/bilibili2233/
      - https://cdn.jsdelivr.net/gh/GamerNoTitle/ValineCDN@master/Menhera-chan
    reaction:
      - https://unpkg.com/@waline/emojis@1.3.0/tieba/tieba_agree.png
      - https://unpkg.com/@waline/emojis@1.3.0/tieba/tieba_doubt.png
      - https://unpkg.com/@waline/emojis@1.3.0/tieba/tieba_heart.png
      - https://unpkg.com/@waline/emojis@1.3.0/tieba/tieba_lovely.png
      - https://unpkg.com/@waline/emojis@1.3.0/tieba/tieba_rage.png
      - https://unpkg.com/@waline/emojis@1.3.0/tieba/tieba_cry.png
      - https://unpkg.com/@waline/emojis@1.3.0/tieba/tieba_awkward.png
      - https://unpkg.com/@waline/emojis@1.3.0/tieba/tieba_vomit.png
sidebar:
  for_page: [lastupdate, notice, tagcloud, webinfo]
  widget_library:
    blogger:
      avatar: https://unpkg.com/mcseekeri@1.2.6/avatar/amadeus.webp
      title: 科学 ADV 图书馆
      subtitle: 致力于科 A 相关内容的搜集与整理
      jinrishici: false
      social:
        - icon: fa-solid fa-envelope
          url: mailto:hiyajo.maho@outlook.jp
        - icon: fab fa-github
          url: https://github.com/mcseekeri/sciadv
    category:
      display: [desktop, mobile]
      header:
        url: /categories/
    tagcloud:
      header:
        url: /tags/
      min_font: 18
      max_font: 26

    qrcode:
      images:
        - https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/qrcode/github@volantis.png
        - https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/qrcode/github@volantis.png
    webinfo:
      display: [desktop, mobile]
      type:
        runtime:
          enable: true
          data: "2021/01/09"
        wordcount:
          enable: true
    notice:
      class: text
      display: [desktop, mobile]
      header:
        icon: fad fa-siren-on
        title: 站点公告
      content:
        - 「然后呢,我,把这个混帐的站点,发布了。」
        - 欢迎来到科学ADV图书馆，本站致力于收集科学ADV系列所有衍生小说。
        - 站点支持离线访问及作为程序安装到设备上，方便用户查询内容。
        - 如果您访问本站遇到了一些问题，请尝试清除浏览器数据之后访问。
        - 预祝看的愉快,有问题欢迎前往[关于页面](/about/)进行留言
tag_plugins:
  note:
    icon: '\f054'
    color: ""
    iconfont: "Font Awesome 6 Pro"
  link:
    placeholder: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/logo/256/safari.png

site_footer:
  layout: [aplayer, badge, br, analytics, copyright, powered]
  source: https://github.com/mcseekeri/sciadv

  copyright: "本站内容来源自网络 所有权归作者所有"
  badge: "[![commit](https://img.shields.io/github/last-commit/MCSeekeri/sciadv?style=for-the-badge)](https://github.com/MCSeekeri/sciadv) [![star](https://img.shields.io/github/stars/MCSeekeri/sciadv?style=for-the-badge)](https://github.com/MCSeekeri/sciadv) [![size](https://img.shields.io/github/repo-size/MCSeekeri/sciadv?style=for-the-badge)](https://github.com/MCSeekeri/sciadv) [![code size](https://img.shields.io/github/languages/code-size/MCSeekeri/sciadv?logo=code%20size&style=for-the-badge)](https://github.com/MCSeekeri/sciadv) [![status](https://img.shields.io/uptimerobot/ratio/m785802121-f726e102d93b206615b80ae4?style=for-the-badge)](https://status.mcseekeri.com/)"
  powered: "[![Powered](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxOTcuMTkiIGhlaWdodD0iMzUiIHZpZXdCb3g9IjAgMCAxOTcuMTkgMzUiPjxyZWN0IGNsYXNzPSJzdmdfX3JlY3QiIHg9IjAiIHk9IjAiIHdpZHRoPSIxMjcuMjUiIGhlaWdodD0iMzUiIGZpbGw9IiM1NTU1NTUiLz48cmVjdCBjbGFzcz0ic3ZnX19yZWN0IiB4PSIxMjUuMjUiIHk9IjAiIHdpZHRoPSI3MS45NCIgaGVpZ2h0PSIzNSIgZmlsbD0iIzM4OUFENSIvPjxwYXRoIGNsYXNzPSJzdmdfX3RleHQiIGQ9Ik0xNS43MCAyMkwxNC4yMiAyMkwxNC4yMiAxMy40N0wxNy40OCAxMy40N1ExOC45MSAxMy40NyAxOS43NSAxNC4yMVEyMC41OSAxNC45NiAyMC41OSAxNi4xOEwyMC41OSAxNi4xOFEyMC41OSAxNy40NCAxOS43NyAxOC4xM1ExOC45NSAxOC44MyAxNy40NiAxOC44M0wxNy40NiAxOC44M0wxNS43MCAxOC44M0wxNS43MCAyMlpNMTUuNzAgMTQuNjZMMTUuNzAgMTcuNjRMMTcuNDggMTcuNjRRMTguMjcgMTcuNjQgMTguNjkgMTcuMjdRMTkuMTAgMTYuOTAgMTkuMTAgMTYuMTlMMTkuMTAgMTYuMTlRMTkuMTAgMTUuNTAgMTguNjggMTUuMDlRMTguMjYgMTQuNjggMTcuNTIgMTQuNjZMMTcuNTIgMTQuNjZMMTUuNzAgMTQuNjZaTTI0LjYxIDE4LjAwTDI0LjYxIDE4LjAwTDI0LjYxIDE3LjUyUTI0LjYxIDE2LjI4IDI1LjA1IDE1LjMyUTI1LjQ5IDE0LjM3IDI2LjMwIDEzLjg2UTI3LjEwIDEzLjM1IDI4LjE0IDEzLjM1UTI5LjE5IDEzLjM1IDI5Ljk5IDEzLjg1UTMwLjgwIDE0LjM1IDMxLjI0IDE1LjI5UTMxLjY4IDE2LjIzIDMxLjY4IDE3LjQ4TDMxLjY4IDE3LjQ4TDMxLjY4IDE3Ljk2UTMxLjY4IDE5LjIxIDMxLjI1IDIwLjE2UTMwLjgyIDIxLjEwIDMwLjAxIDIxLjYxUTI5LjIxIDIyLjEyIDI4LjE2IDIyLjEyTDI4LjE2IDIyLjEyUTI3LjEyIDIyLjEyIDI2LjMxIDIxLjYxUTI1LjUwIDIxLjEwIDI1LjA1IDIwLjE3UTI0LjYxIDE5LjIzIDI0LjYxIDE4LjAwWk0yNi4wOSAxNy40NkwyNi4wOSAxNy45NlEyNi4wOSAxOS4zNiAyNi42NCAyMC4xM1EyNy4xOCAyMC45MCAyOC4xNiAyMC45MEwyOC4xNiAyMC45MFEyOS4xNCAyMC45MCAyOS42NyAyMC4xNVEzMC4yMCAxOS40MCAzMC4yMCAxNy45NkwzMC4yMCAxNy45NkwzMC4yMCAxNy41MVEzMC4yMCAxNi4wOSAyOS42NyAxNS4zNFEyOS4xMyAxNC41OCAyOC4xNCAxNC41OEwyOC4xNCAxNC41OFEyNy4xOCAxNC41OCAyNi42NCAxNS4zM1EyNi4xMCAxNi4wOSAyNi4wOSAxNy40NkwyNi4wOSAxNy40NlpNMzcuNTMgMjJMMzUuNTYgMTMuNDdMMzcuMDMgMTMuNDdMMzguMzYgMTkuODhMMzkuOTkgMTMuNDdMNDEuMjMgMTMuNDdMNDIuODQgMTkuODlMNDQuMTUgMTMuNDdMNDUuNjIgMTMuNDdMNDMuNjUgMjJMNDIuMjQgMjJMNDAuNjEgMTUuNzdMMzguOTYgMjJMMzcuNTMgMjJaTTU1LjI3IDIyTDQ5LjcwIDIyTDQ5LjcwIDEzLjQ3TDU1LjIzIDEzLjQ3TDU1LjIzIDE0LjY2TDUxLjE4IDE0LjY2TDUxLjE4IDE3LjAyTDU0LjY4IDE3LjAyTDU0LjY4IDE4LjE5TDUxLjE4IDE4LjE5TDUxLjE4IDIwLjgyTDU1LjI3IDIwLjgyTDU1LjI3IDIyWk02MC45NSAyMkw1OS40NyAyMkw1OS40NyAxMy40N0w2Mi40NyAxMy40N1E2My45NSAxMy40NyA2NC43NSAxNC4xM1E2NS41NSAxNC43OSA2NS41NSAxNi4wNUw2NS41NSAxNi4wNVE2NS41NSAxNi45MCA2NS4xNCAxNy40OFE2NC43MiAxOC4wNiA2My45OSAxOC4zN0w2My45OSAxOC4zN0w2NS45MCAyMS45Mkw2NS45MCAyMkw2NC4zMSAyMkw2Mi42MCAxOC43MUw2MC45NSAxOC43MUw2MC45NSAyMlpNNjAuOTUgMTQuNjZMNjAuOTUgMTcuNTJMNjIuNDggMTcuNTJRNjMuMjMgMTcuNTIgNjMuNjUgMTcuMTVRNjQuMDcgMTYuNzcgNjQuMDcgMTYuMTFMNjQuMDcgMTYuMTFRNjQuMDcgMTUuNDMgNjMuNjggMTUuMDVRNjMuMjkgMTQuNjggNjIuNTIgMTQuNjZMNjIuNTIgMTQuNjZMNjAuOTUgMTQuNjZaTTc1LjUyIDIyTDY5Ljk1IDIyTDY5Ljk1IDEzLjQ3TDc1LjQ4IDEzLjQ3TDc1LjQ4IDE0LjY2TDcxLjQzIDE0LjY2TDcxLjQzIDE3LjAyTDc0LjkzIDE3LjAyTDc0LjkzIDE4LjE5TDcxLjQzIDE4LjE5TDcxLjQzIDIwLjgyTDc1LjUyIDIwLjgyTDc1LjUyIDIyWk04Mi4xNyAyMkw3OS43MiAyMkw3OS43MiAxMy40N0w4Mi4yNCAxMy40N1E4My4zNyAxMy40NyA4NC4yNSAxMy45N1E4NS4xMiAxNC40OCA4NS42MCAxNS40MFE4Ni4wOCAxNi4zMyA4Ni4wOCAxNy41Mkw4Ni4wOCAxNy41Mkw4Ni4wOCAxNy45NVE4Ni4wOCAxOS4xNiA4NS42MCAyMC4wOFE4NS4xMiAyMS4wMCA4NC4yMiAyMS41MFE4My4zMyAyMiA4Mi4xNyAyMkw4Mi4xNyAyMlpNODEuMjAgMTQuNjZMODEuMjAgMjAuODJMODIuMTcgMjAuODJRODMuMzMgMjAuODIgODMuOTYgMjAuMDlRODQuNTggMTkuMzYgODQuNTkgMTcuOTlMODQuNTkgMTcuOTlMODQuNTkgMTcuNTJRODQuNTkgMTYuMTMgODMuOTkgMTUuNDBRODMuMzkgMTQuNjYgODIuMjQgMTQuNjZMODIuMjQgMTQuNjZMODEuMjAgMTQuNjZaTTk5LjY0IDIyTDk2LjUyIDIyTDk2LjUyIDEzLjQ3TDk5LjQ1IDEzLjQ3UTEwMC44OSAxMy40NyAxMDEuNjUgMTQuMDVRMTAyLjQxIDE0LjYzIDEwMi40MSAxNS43OEwxMDIuNDEgMTUuNzhRMTAyLjQxIDE2LjM2IDEwMi4wOSAxNi44M1ExMDEuNzcgMTcuMzAgMTAxLjE2IDE3LjU2TDEwMS4xNiAxNy41NlExMDEuODYgMTcuNzUgMTAyLjIzIDE4LjI2UTEwMi42MSAxOC43OCAxMDIuNjEgMTkuNTFMMTAyLjYxIDE5LjUxUTEwMi42MSAyMC43MSAxMDEuODQgMjEuMzZRMTAxLjA3IDIyIDk5LjY0IDIyTDk5LjY0IDIyWk05OC4wMSAxOC4xNUw5OC4wMSAyMC44Mkw5OS42NSAyMC44MlExMDAuMzUgMjAuODIgMTAwLjc0IDIwLjQ3UTEwMS4xNCAyMC4xMyAxMDEuMTQgMTkuNTFMMTAxLjE0IDE5LjUxUTEwMS4xNCAxOC4xOCA5OS43OCAxOC4xNUw5OS43OCAxOC4xNUw5OC4wMSAxOC4xNVpNOTguMDEgMTQuNjZMOTguMDEgMTcuMDZMOTkuNDYgMTcuMDZRMTAwLjE1IDE3LjA2IDEwMC41NCAxNi43NVExMDAuOTMgMTYuNDMgMTAwLjkzIDE1Ljg2TDEwMC45MyAxNS44NlExMDAuOTMgMTUuMjMgMTAwLjU3IDE0Ljk1UTEwMC4yMSAxNC42NiA5OS40NSAxNC42Nkw5OS40NSAxNC42Nkw5OC4wMSAxNC42NlpNMTA5LjEyIDE4Ljg2TDEwNi4yNiAxMy40N0wxMDcuOTAgMTMuNDdMMTA5Ljg3IDE3LjUxTDExMS44MyAxMy40N0wxMTMuNDcgMTMuNDdMMTEwLjYxIDE4Ljg2TDExMC42MSAyMkwxMDkuMTIgMjJMMTA5LjEyIDE4Ljg2WiIgZmlsbD0iI0ZGRkZGRiIvPjxwYXRoIGNsYXNzPSJzdmdfX3RleHQiIGQ9Ik0xNDEuODIgMjJMMTM5LjQ0IDIyTDEzOS40NCAxMy42MEwxNDEuODIgMTMuNjBMMTQxLjgyIDE2Ljc2TDE0NS4wNiAxNi43NkwxNDUuMDYgMTMuNjBMMTQ3LjQzIDEzLjYwTDE0Ny40MyAyMkwxNDUuMDYgMjJMMTQ1LjA2IDE4LjcyTDE0MS44MiAxOC43MkwxNDEuODIgMjJaTTE1OS4zNCAyMkwxNTIuNTkgMjJMMTUyLjU5IDEzLjYwTDE1OS4xOCAxMy42MEwxNTkuMTggMTUuNDRMMTU0Ljk1IDE1LjQ0TDE1NC45NSAxNi44NUwxNTguNjggMTYuODVMMTU4LjY4IDE4LjYzTDE1NC45NSAxOC42M0wxNTQuOTUgMjAuMTdMMTU5LjM0IDIwLjE3TDE1OS4zNCAyMlpNMTY1Ljk5IDIyTDE2My4yOCAyMkwxNjYuMzQgMTcuNzVMMTYzLjQxIDEzLjYwTDE2Ni4wOSAxMy42MEwxNjcuNzcgMTYuMDJMMTY5LjQyIDEzLjYwTDE3MS45OSAxMy42MEwxNjkuMDYgMTcuNjZMMTcyLjE5IDIyTDE2OS40NSAyMkwxNjcuNzEgMTkuNDBMMTY1Ljk5IDIyWk0xNzYuMDQgMTcuODBMMTc2LjA0IDE3LjgwUTE3Ni4wNCAxNi41NSAxNzYuNjQgMTUuNTVRMTc3LjI1IDE0LjU2IDE3OC4zMSAxNC4wMFExNzkuMzggMTMuNDMgMTgwLjcxIDEzLjQzTDE4MC43MSAxMy40M1ExODIuMDQgMTMuNDMgMTgzLjEwIDE0LjAwUTE4NC4xNiAxNC41NiAxODQuNzcgMTUuNTVRMTg1LjM4IDE2LjU1IDE4NS4zOCAxNy44MEwxODUuMzggMTcuODBRMTg1LjM4IDE5LjA1IDE4NC43NyAyMC4wNFExODQuMTYgMjEuMDQgMTgzLjEwIDIxLjYwUTE4Mi4wNCAyMi4xNyAxODAuNzEgMjIuMTdMMTgwLjcxIDIyLjE3UTE3OS4zOCAyMi4xNyAxNzguMzEgMjEuNjBRMTc3LjI1IDIxLjA0IDE3Ni42NCAyMC4wNFExNzYuMDQgMTkuMDUgMTc2LjA0IDE3LjgwWk0xNzguNDQgMTcuODBMMTc4LjQ0IDE3LjgwUTE3OC40NCAxOC41MSAxNzguNzQgMTkuMDVRMTc5LjA0IDE5LjYwIDE3OS41NiAxOS45MFExODAuMDcgMjAuMjAgMTgwLjcxIDIwLjIwTDE4MC43MSAyMC4yMFExODEuMzQgMjAuMjAgMTgxLjg2IDE5LjkwUTE4Mi4zOCAxOS42MCAxODIuNjcgMTkuMDVRMTgyLjk3IDE4LjUxIDE4Mi45NyAxNy44MEwxODIuOTcgMTcuODBRMTgyLjk3IDE3LjA5IDE4Mi42NyAxNi41NFExODIuMzggMTYgMTgxLjg2IDE1LjcwUTE4MS4zNCAxNS40MCAxODAuNzEgMTUuNDBMMTgwLjcxIDE1LjQwUTE4MC4wNyAxNS40MCAxNzkuNTUgMTUuNzBRMTc5LjA0IDE2IDE3OC43NCAxNi41NFExNzguNDQgMTcuMDkgMTc4LjQ0IDE3LjgwWiIgZmlsbD0iI0ZGRkZGRiIgeD0iMTM4LjI1Ii8+PC9zdmc+)](https://hexo.io)"

plugins:
  sitesjs:
    enable: false
  friendsjs:
    enable: false
  contributorsjs:
    enable: false

  lazyload:
    onlypost: true

  prismjs:
    copy_code: false
    js:
      - https://unpkg.com/prismjs/components/prism-core.min.js
      - https://unpkg.com/prismjs/plugins/autoloader/prism-autoloader.min.js
      - https://unpkg.com/prismjs/plugins/line-numbers/prism-line-numbers.min.js
    css:
      - https://unpkg.com/prismjs/themes/prism-dark.css
      - https://unpkg.com/prismjs/plugins/line-numbers/prism-line-numbers.css

  scrollreveal:
    enable: true
    distance: 32px
    duration: 500
  wordcount:
    enable: true
  busuanzi:
    enable: true

  nodewaves:
    enable: true

  parallax:
    images:
      - https://unpkg.com/mcseekeri@1.2.6/img/cover/cover1.webp
      - https://unpkg.com/mcseekeri@1.2.6/img/cover/cover2.webp
      - https://unpkg.com/mcseekeri@1.2.6/img/cover/cover3.webp
      - https://unpkg.com/mcseekeri@1.2.6/img/cover/cover4.webp
      - https://unpkg.com/mcseekeri@1.2.6/img/cover/cover5.webp
      - https://unpkg.com/mcseekeri@1.2.6/img/cover/cover6.webp
      - https://unpkg.com/mcseekeri@1.2.6/img/cover/cover7.webp
      - https://unpkg.com/mcseekeri@1.2.6/img/cover/cover8.webp
      - https://unpkg.com/mcseekeri@1.2.6/img/cover/cover9.webp
      - https://unpkg.com/mcseekeri@1.2.6/img/cover/cover10.webp
      - https://unpkg.com/mcseekeri@1.2.6/img/cover/cover11.webp
      - https://unpkg.com/mcseekeri@1.2.6/img/cover/cover12.webp
      - https://unpkg.com/mcseekeri@1.2.6/img/cover/cover13.webp
      - https://unpkg.com/mcseekeri@1.2.6/img/cover/cover14.webp
      - https://unpkg.com/mcseekeri@1.2.6/img/cover/cover15.webp
      - https://unpkg.com/mcseekeri@1.2.6/img/cover/cover16.webp
  aplayer:
    enable: true
    id: 6608242431
    fixed: true
    autoHide: false

  darkmode:
    enable: true

  killNoScript:
    enable: false
  message:
    enable: true
  tidio:
    id: cfeex4okbrrdpt6edk1w3hfsbymjft8x
  menus:
    link:
      - {
          id: "source_docs",
          name: "本站源码",
          icon: "fa-solid fa-code-branch",
          link: "https://github.com/mcseekeri/sciadv",
          group: "link",
        }
custom_css:
  scrollbar:
    size: 12px
    border: 3px
  body:
    effect: [shadow]
  fontfamily:
    logofont:
      fontfamily: '"Roboto", "Noto Serif SC", "PingFang SC", "Microsoft Yahei UI", "Microsoft Yahei", sans-serif'
    bodyfont:
      fontfamily: '"Roboto", "Noto Serif SC", "PingFang SC", "Microsoft Yahei UI", "Microsoft Yahei", sans-serif'
    codefont:
      fontfamily: '"Roboto", "Noto Serif SC", "PingFang SC", "Microsoft Yahei UI", "Microsoft Yahei", sans-serif'
seo:
  robots:
    home_other_pages: index,follow
    archive: index,follow
    category: index,follow
    tag: index,follow

open_graph:
  image: /favicon.ico
structured_data:
  enable: false
  data:
    person:
      sns:
        - https://github.com/MCSeekeri
    logo:
      path: /favicon.ico
