name = "sciadv"
type = "webpack"
account_id = "e948fb59c8aa2a756017549554f66d6a"
workers_dev = true
route = "lib.sci-adv.cc/*"
zone_id = "141fef83655fc53535fb1d8e5884464f"

[site]
bucket = "./public"
entry-point = "workers-site"
