name = "sciadv"
type = "webpack"
account_id = "e948fb59c8aa2a756017549554f66d6a"
workers_dev = false
route = "sciadv.mcseekeri.top/*"
zone_id = "1accbbb71cfa999af490708dd3973acb"

[site]
bucket = "./public"
entry-point = "workers-site"
