name: sciadv-sw
catch_rules: 
    - rule: ^https\:\/\/((cdn|fastly|gcore|test1|quantil)\.jsdelivr\.net\/npm|unpkg\.com|npm\.elemecdn\.com)
      transform_rules:
      - search: _
        replace:
          - https://unpkg.com
          - https://npm.elemecdn.com 
          - https://unpkg.onmicrosoft.cn
          - https://npm.sourcegcdn.com 
        action: fetch
        fetch:
          status: 200
          preflight: false
          engine: parallel
          timeout: 5000
          expire: 1000*60*60
  
    - rule: .*
      transform_rules:
      - search: .*
        action: skip